---
- name: Deploy Chat App (Auto-detect entry point)
  hosts: chatapp
  become: yes
  vars:
    app_user: ec2-user
    app_dir: /home/ec2-user/chatapp

  tasks:
    - name: Ensure app directory exists and is updated
      git:
        repo: https://github.com/bodukal/chatapp.git
        dest: "{{ app_dir }}"
        force: yes
      become_user: "{{ app_user }}"

    - name: Install app dependencies
      npm:
        path: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Install PM2 globally
      npm:
                                                              1,1           Top

